'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace ResourcesT
    
    'This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    'To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    'Copyright (c) Dmytro Kryvko 2006-2008 (http://dmytro.kryvko.googlepages.com/)
    '''<summary>
    '''A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "2.2.5.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")>  _
    Public Class ExceptionsWin
        
        Private Shared _resourceManager As Global.System.Resources.ResourceManager
        
        Private Shared _internalSyncObject As Object
        
        Private Shared _resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''Thread safe lock object used by this class.
        '''</summary>
        Public Shared ReadOnly Property InternalSyncObject() As Object
            Get
                If Object.ReferenceEquals(_internalSyncObject, Nothing) Then
                    Global.System.Threading.Interlocked.CompareExchange(_internalSyncObject, New Object, Nothing)
                End If
                Return _internalSyncObject
            End Get
        End Property
        
        '''<summary>
        '''Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(_resourceManager, Nothing) Then
                    Global.System.Threading.Monitor.Enter(InternalSyncObject)
                    Try 
                        If Object.ReferenceEquals(_resourceManager, Nothing) Then
                            Global.System.Threading.Interlocked.Exchange(_resourceManager, New Global.System.Resources.ResourceManager("Tools.ResourcesT.ExceptionsWin", GetType(ExceptionsWin).Assembly))
                        End If
                    Finally
                        Global.System.Threading.Monitor.Exit(InternalSyncObject)
                    End Try
                End If
                Return _resourceManager
            End Get
        End Property
        
        '''<summary>
        '''Overrides the current thread's CurrentUICulture property for all
        '''resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return _resourceCulture
            End Get
            Set
                _resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''Looks up a localized string similar to 'Additional events have been already called.'.
        '''</summary>
        Public Shared ReadOnly Property AdditionalEventsHaveBeenAlreadyCalled() As String
            Get
                Return ResourceManager.GetString("AdditionalEventsHaveBeenAlreadyCalled", _resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Looks up a localized string similar to 'Cannot convert RAWINPUT_Marshalling to RAWINPUT_NonMarshalling when it contains HID data'.
        '''</summary>
        Public Shared ReadOnly Property CannotConvertRAWINPUTMarshallingToRAWINPUTNonMarshalling() As String
            Get
                Return ResourceManager.GetString("CannotConvertRAWINPUTMarshallingToRAWINPUTNonMarshalling", _resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Looks up a localized string similar to 'Cannot create link from file {0}.'.
        '''</summary>
        Public Shared ReadOnly Property CannotCreateLinkFromFile0() As String
            Get
                Return ResourceManager.GetString("CannotCreateLinkFromFile0", _resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Looks up a localized string similar to 'Devices can be excluded only from usage pages being registered in same batch.'.
        '''</summary>
        Public Shared ReadOnly Property DevicesCanBeExcludedOnlyFromUsagePagesBeingRegistered() As String
            Get
                Return ResourceManager.GetString("DevicesCanBeExcludedOnlyFromUsagePagesBeingRegistered", _resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Looks up a localized string similar to 'Device with Exclude set to true must have Usage set to zero.'.
        '''</summary>
        Public Shared ReadOnly Property DeviceWithExcludeSetToTrueMustHaveUsageSetToZero() As String
            Get
                Return ResourceManager.GetString("DeviceWithExcludeSetToTrueMustHaveUsageSetToZero", _resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Looks up a localized string similar to 'Given owner has already attached RawInputEventProvider'.
        '''</summary>
        Public Shared ReadOnly Property GivenOwnerHasAlreadyAttachedRawInputEventProvider() As String
            Get
                Return ResourceManager.GetString("GivenOwnerHasAlreadyAttachedRawInputEventProvider", _resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Looks up a localized string similar to 'Hook is already registered for this instance.'.
        '''</summary>
        Public Shared ReadOnly Property HookIsAlreadyRegisteredForThisInstance() As String
            Get
                Return ResourceManager.GetString("HookIsAlreadyRegisteredForThisInstance", _resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Looks up a localized string similar to 'Hook is not registered for this instance'.
        '''</summary>
        Public Shared ReadOnly Property HookIsNotRegisteredForThisInstance() As String
            Get
                Return ResourceManager.GetString("HookIsNotRegisteredForThisInstance", _resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Looks up a localized string similar to 'Hotkey must include a modifier key.'.
        '''</summary>
        Public Shared ReadOnly Property HotkeyMustIncludeAModifierKey() As String
            Get
                Return ResourceManager.GetString("HotkeyMustIncludeAModifierKey", _resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Looks up a localized string similar to '{0} is invalid key. Keys must be within range from 0 to 255.'.
        '''</summary>
        Public Shared ReadOnly Property IsInvalidKeyKeysMustBeWithinRangeFrom0To255() As String
            Get
                Return ResourceManager.GetString("IsInvalidKeyKeysMustBeWithinRangeFrom0To255", _resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Looks up a localized string similar to '{0} is unknown registry base key'.
        '''</summary>
        Public Shared ReadOnly Property IsUnknownRegistryBaseKey() As String
            Get
                Return ResourceManager.GetString("IsUnknownRegistryBaseKey", _resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Looks up a localized string similar to 'Legacy messages can be disabled only for keyboard and mouse device, or when whole generic desktop controls usage page is being registered.'.
        '''</summary>
        Public Shared ReadOnly Property LegacyMessagesCanBeDisabledOnlyForKeyboardAndMouseDevice() As String
            Get
                Return ResourceManager.GetString("LegacyMessagesCanBeDisabledOnlyForKeyboardAndMouseDevice", _resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Looks up a localized string similar to 'Lenght of Original.RawItemsCount must be 1 and Original.RawItemSize must be 2 or 3.'.
        '''</summary>
        Public Shared ReadOnly Property LenghtOfOriginalRawItemsCountMustBe1AndOriginalRawItemSize() As String
            Get
                Return ResourceManager.GetString("LenghtOfOriginalRawItemsCountMustBe1AndOriginalRawItemSize", _resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Looks up a localized string similar to 'Message target window handle must be same as handle of window this instance was created for'.
        '''</summary>
        Public Shared ReadOnly Property MessageTargetWindowHandleMustBeSameAsHandleOfWindow() As String
            Get
                Return ResourceManager.GetString("MessageTargetWindowHandleMustBeSameAsHandleOfWindow", _resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Looks up a localized string similar to 'Owher handle has changed.'.
        '''</summary>
        Public Shared ReadOnly Property OwherHandleHasChanged() As String
            Get
                Return ResourceManager.GetString("OwherHandleHasChanged", _resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Looks up a localized string similar to 'Raw device name has invalid format. It should consist of 4 parte separated by #.'.
        '''</summary>
        Public Shared ReadOnly Property RawDeviceNameHasInvalidFormatItShouldConsistOf4Parte() As String
            Get
                Return ResourceManager.GetString("RawDeviceNameHasInvalidFormatItShouldConsistOf4Parte", _resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Looks up a localized string similar to 'Raw device name has unexpected format. It must start with &quot;{0}&quot;.'.
        '''</summary>
        Public Shared ReadOnly Property RawDeviceNameHasUnexpectedFormatItMustStartWith0() As String
            Get
                Return ResourceManager.GetString("RawDeviceNameHasUnexpectedFormatItMustStartWith0", _resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Looks up a localized string similar to 'Source of window message evnt must be same as owner ow this instance'.
        '''</summary>
        Public Shared ReadOnly Property SourceOfWindowMessageEvntMustBeSameAsOwnerOwThisInstance() As String
            Get
                Return ResourceManager.GetString("SourceOfWindowMessageEvntMustBeSameAsOwnerOwThisInstance", _resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Looks up a localized string similar to 'The calass guid part of device name is in invalid format. See InnerException for details.'.
        '''</summary>
        Public Shared ReadOnly Property TheCalassGuidPartOfDeviceNameIsInInvalidFormatSeeInnerException() As String
            Get
                Return ResourceManager.GetString("TheCalassGuidPartOfDeviceNameIsInInvalidFormatSeeInnerException", _resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Looks up a localized string similar to 'Unable to obtain handle to system menu.'.
        '''</summary>
        Public Shared ReadOnly Property UnableToObtainHandleToSystemMenu() As String
            Get
                Return ResourceManager.GetString("UnableToObtainHandleToSystemMenu", _resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Looks up a localized string similar to 'Unknown raw input device type {0}'.
        '''</summary>
        Public Shared ReadOnly Property UnknownRawInputDeviceType0() As String
            Get
                Return ResourceManager.GetString("UnknownRawInputDeviceType0", _resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Looks up a localized string similar to 'When only one device is being (un)registered, it cannot have Exclude set to true.'.
        '''</summary>
        Public Shared ReadOnly Property WhenOnlyOneDeviceIsBeingUnRegisteredItCannotHaveExclude() As String
            Get
                Return ResourceManager.GetString("WhenOnlyOneDeviceIsBeingUnRegisteredItCannotHaveExclude", _resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''The stub formatting method returning the AdditionalEventsHaveBeenAlreadyCalled property value.
        '''</summary>
        '''<returns>The AdditionalEventsHaveBeenAlreadyCalled property value.</returns>
        Public Shared Function AdditionalEventsHaveBeenAlreadyCalledFormat() As String
            Return AdditionalEventsHaveBeenAlreadyCalled
        End Function
        
        '''<summary>
        '''The stub formatting method returning the CannotConvertRAWINPUTMarshallingToRAWINPUTNonMarshalling property value.
        '''</summary>
        '''<returns>The CannotConvertRAWINPUTMarshallingToRAWINPUTNonMarshalling property value.</returns>
        Public Shared Function CannotConvertRAWINPUTMarshallingToRAWINPUTNonMarshallingFormat() As String
            Return CannotConvertRAWINPUTMarshallingToRAWINPUTNonMarshalling
        End Function
        
        '''<summary>
        '''Formats a localized string similar to 'Cannot create link from file {0}.'.
        '''</summary>
        '''<param name="arg0">An object (0) to format.</param>
        '''<returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        Public Shared Function CannotCreateLinkFromFile0Format(ByVal arg0 As Object) As String
            Return String.Format(_resourceCulture, CannotCreateLinkFromFile0, arg0)
        End Function
        
        '''<summary>
        '''The stub formatting method returning the DevicesCanBeExcludedOnlyFromUsagePagesBeingRegistered property value.
        '''</summary>
        '''<returns>The DevicesCanBeExcludedOnlyFromUsagePagesBeingRegistered property value.</returns>
        Public Shared Function DevicesCanBeExcludedOnlyFromUsagePagesBeingRegisteredFormat() As String
            Return DevicesCanBeExcludedOnlyFromUsagePagesBeingRegistered
        End Function
        
        '''<summary>
        '''The stub formatting method returning the DeviceWithExcludeSetToTrueMustHaveUsageSetToZero property value.
        '''</summary>
        '''<returns>The DeviceWithExcludeSetToTrueMustHaveUsageSetToZero property value.</returns>
        Public Shared Function DeviceWithExcludeSetToTrueMustHaveUsageSetToZeroFormat() As String
            Return DeviceWithExcludeSetToTrueMustHaveUsageSetToZero
        End Function
        
        '''<summary>
        '''The stub formatting method returning the GivenOwnerHasAlreadyAttachedRawInputEventProvider property value.
        '''</summary>
        '''<returns>The GivenOwnerHasAlreadyAttachedRawInputEventProvider property value.</returns>
        Public Shared Function GivenOwnerHasAlreadyAttachedRawInputEventProviderFormat() As String
            Return GivenOwnerHasAlreadyAttachedRawInputEventProvider
        End Function
        
        '''<summary>
        '''The stub formatting method returning the HookIsAlreadyRegisteredForThisInstance property value.
        '''</summary>
        '''<returns>The HookIsAlreadyRegisteredForThisInstance property value.</returns>
        Public Shared Function HookIsAlreadyRegisteredForThisInstanceFormat() As String
            Return HookIsAlreadyRegisteredForThisInstance
        End Function
        
        '''<summary>
        '''The stub formatting method returning the HookIsNotRegisteredForThisInstance property value.
        '''</summary>
        '''<returns>The HookIsNotRegisteredForThisInstance property value.</returns>
        Public Shared Function HookIsNotRegisteredForThisInstanceFormat() As String
            Return HookIsNotRegisteredForThisInstance
        End Function
        
        '''<summary>
        '''The stub formatting method returning the HotkeyMustIncludeAModifierKey property value.
        '''</summary>
        '''<returns>The HotkeyMustIncludeAModifierKey property value.</returns>
        Public Shared Function HotkeyMustIncludeAModifierKeyFormat() As String
            Return HotkeyMustIncludeAModifierKey
        End Function
        
        '''<summary>
        '''Formats a localized string similar to '{0} is invalid key. Keys must be within range from 0 to 255.'.
        '''</summary>
        '''<param name="arg0">An object (0) to format.</param>
        '''<returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        Public Shared Function IsInvalidKeyKeysMustBeWithinRangeFrom0To255Format(ByVal arg0 As Object) As String
            Return String.Format(_resourceCulture, IsInvalidKeyKeysMustBeWithinRangeFrom0To255, arg0)
        End Function
        
        '''<summary>
        '''Formats a localized string similar to '{0} is unknown registry base key'.
        '''</summary>
        '''<param name="arg0">An object (0) to format.</param>
        '''<returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        Public Shared Function IsUnknownRegistryBaseKeyFormat(ByVal arg0 As Object) As String
            Return String.Format(_resourceCulture, IsUnknownRegistryBaseKey, arg0)
        End Function
        
        '''<summary>
        '''The stub formatting method returning the LegacyMessagesCanBeDisabledOnlyForKeyboardAndMouseDevice property value.
        '''</summary>
        '''<returns>The LegacyMessagesCanBeDisabledOnlyForKeyboardAndMouseDevice property value.</returns>
        Public Shared Function LegacyMessagesCanBeDisabledOnlyForKeyboardAndMouseDeviceFormat() As String
            Return LegacyMessagesCanBeDisabledOnlyForKeyboardAndMouseDevice
        End Function
        
        '''<summary>
        '''The stub formatting method returning the LenghtOfOriginalRawItemsCountMustBe1AndOriginalRawItemSize property value.
        '''</summary>
        '''<returns>The LenghtOfOriginalRawItemsCountMustBe1AndOriginalRawItemSize property value.</returns>
        Public Shared Function LenghtOfOriginalRawItemsCountMustBe1AndOriginalRawItemSizeFormat() As String
            Return LenghtOfOriginalRawItemsCountMustBe1AndOriginalRawItemSize
        End Function
        
        '''<summary>
        '''The stub formatting method returning the MessageTargetWindowHandleMustBeSameAsHandleOfWindow property value.
        '''</summary>
        '''<returns>The MessageTargetWindowHandleMustBeSameAsHandleOfWindow property value.</returns>
        Public Shared Function MessageTargetWindowHandleMustBeSameAsHandleOfWindowFormat() As String
            Return MessageTargetWindowHandleMustBeSameAsHandleOfWindow
        End Function
        
        '''<summary>
        '''The stub formatting method returning the OwherHandleHasChanged property value.
        '''</summary>
        '''<returns>The OwherHandleHasChanged property value.</returns>
        Public Shared Function OwherHandleHasChangedFormat() As String
            Return OwherHandleHasChanged
        End Function
        
        '''<summary>
        '''The stub formatting method returning the RawDeviceNameHasInvalidFormatItShouldConsistOf4Parte property value.
        '''</summary>
        '''<returns>The RawDeviceNameHasInvalidFormatItShouldConsistOf4Parte property value.</returns>
        Public Shared Function RawDeviceNameHasInvalidFormatItShouldConsistOf4ParteFormat() As String
            Return RawDeviceNameHasInvalidFormatItShouldConsistOf4Parte
        End Function
        
        '''<summary>
        '''Formats a localized string similar to 'Raw device name has unexpected format. It must start with &quot;{0}&quot;.'.
        '''</summary>
        '''<param name="arg0">An object (0) to format.</param>
        '''<returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        Public Shared Function RawDeviceNameHasUnexpectedFormatItMustStartWith0Format(ByVal arg0 As Object) As String
            Return String.Format(_resourceCulture, RawDeviceNameHasUnexpectedFormatItMustStartWith0, arg0)
        End Function
        
        '''<summary>
        '''The stub formatting method returning the SourceOfWindowMessageEvntMustBeSameAsOwnerOwThisInstance property value.
        '''</summary>
        '''<returns>The SourceOfWindowMessageEvntMustBeSameAsOwnerOwThisInstance property value.</returns>
        Public Shared Function SourceOfWindowMessageEvntMustBeSameAsOwnerOwThisInstanceFormat() As String
            Return SourceOfWindowMessageEvntMustBeSameAsOwnerOwThisInstance
        End Function
        
        '''<summary>
        '''The stub formatting method returning the TheCalassGuidPartOfDeviceNameIsInInvalidFormatSeeInnerException property value.
        '''</summary>
        '''<returns>The TheCalassGuidPartOfDeviceNameIsInInvalidFormatSeeInnerException property value.</returns>
        Public Shared Function TheCalassGuidPartOfDeviceNameIsInInvalidFormatSeeInnerExceptionFormat() As String
            Return TheCalassGuidPartOfDeviceNameIsInInvalidFormatSeeInnerException
        End Function
        
        '''<summary>
        '''The stub formatting method returning the UnableToObtainHandleToSystemMenu property value.
        '''</summary>
        '''<returns>The UnableToObtainHandleToSystemMenu property value.</returns>
        Public Shared Function UnableToObtainHandleToSystemMenuFormat() As String
            Return UnableToObtainHandleToSystemMenu
        End Function
        
        '''<summary>
        '''Formats a localized string similar to 'Unknown raw input device type {0}'.
        '''</summary>
        '''<param name="arg0">An object (0) to format.</param>
        '''<returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        Public Shared Function UnknownRawInputDeviceType0Format(ByVal arg0 As Object) As String
            Return String.Format(_resourceCulture, UnknownRawInputDeviceType0, arg0)
        End Function
        
        '''<summary>
        '''The stub formatting method returning the WhenOnlyOneDeviceIsBeingUnRegisteredItCannotHaveExclude property value.
        '''</summary>
        '''<returns>The WhenOnlyOneDeviceIsBeingUnRegisteredItCannotHaveExclude property value.</returns>
        Public Shared Function WhenOnlyOneDeviceIsBeingUnRegisteredItCannotHaveExcludeFormat() As String
            Return WhenOnlyOneDeviceIsBeingUnRegisteredItCannotHaveExclude
        End Function
    End Class
End Namespace
