#pragma once

#using <mscorlib.dll>
#using <System.dll>

using namespace System::Security::Permissions;
[assembly:SecurityPermissionAttribute(SecurityAction::RequestMinimum, SkipVerification=false)];
namespace Tools {
    namespace TotalCommanderT {
        namespace ResourcesT {
    using namespace System;
    using namespace System;
    ref class Exceptions;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2009 (http://dmytro.kryvko.googlepages.com/)
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", L"2.2.5.0"), 
    System::Diagnostics::DebuggerNonUserCodeAttribute, 
    System::Diagnostics::CodeAnalysis::SuppressMessageAttribute(L"Microsoft.Naming", L"CA1724:TypeNamesShouldNotMatchNamespaces")]
    public ref class Exceptions {
        
        private: static ::System::Resources::ResourceManager^  _resourceManager;
        
        private: static ::System::Object^  _internalSyncObject;
        
        private: static ::System::Globalization::CultureInfo^  _resourceCulture;
        
        internal: [System::Diagnostics::CodeAnalysis::SuppressMessageAttribute(L"Microsoft.Performance", L"CA1811:AvoidUncalledPrivateCode")]
        Exceptions();
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public: static property ::System::Object^  InternalSyncObject {
            ::System::Object^  get();
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        public: [System::ComponentModel::EditorBrowsableAttribute(::System::ComponentModel::EditorBrowsableState::Advanced)]
        static property ::System::Resources::ResourceManager^  ResourceManager {
            ::System::Resources::ResourceManager^  get();
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        public: [System::ComponentModel::EditorBrowsableAttribute(::System::ComponentModel::EditorBrowsableState::Advanced)]
        static property ::System::Globalization::CultureInfo^  Culture {
            ::System::Globalization::CultureInfo^  get();
            System::Void set(::System::Globalization::CultureInfo^  value);
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Plugin was not initialized.'.
        /// </summary>
        public: static property System::String^  PluginNotInitialized {
            System::String^  get();
        }
        
        /// <summary>
        /// The stub formatting method returning the PluginNotInitialized property value.
        /// </summary>
        /// <returns>The PluginNotInitialized property value.</returns>
        public: static System::String^  PluginNotInitializedFormat();
    };
        }
    }
}