'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3031
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace ResourcesT
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Components
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Tools.Components", GetType(Components).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Accessibility.
        '''</summary>
        Friend Shared ReadOnly Property Accessibility_cat() As String
            Get
                Return ResourceManager.GetString("Accessibility_cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Access character for the button. Should be one of characters from button text..
        '''</summary>
        Friend Shared ReadOnly Property AccessKey_d() As String
            Get
                Return ResourceManager.GetString("AccessKey_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Action.
        '''</summary>
        Friend Shared ReadOnly Property Action_cat() As String
            Get
                Return ResourceManager.GetString("Action_cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Value indicationg if dialog can be closed without clicking on button. Thi is typically by closing the window that represents the dialog by the &quot;X&quot; button..
        '''</summary>
        Friend Shared ReadOnly Property AllowClose_d() As String
            Get
                Return ResourceManager.GetString("AllowClose_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Appearance.
        '''</summary>
        Friend Shared ReadOnly Property Appearance_cat() As String
            Get
                Return ResourceManager.GetString("Appearance_cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Asterisk.
        '''</summary>
        Friend Shared ReadOnly Property Asterisk() As String
            Get
                Return ResourceManager.GetString("Asterisk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Asynchronous.
        '''</summary>
        Friend Shared ReadOnly Property Asynchronous_cat() As String
            Get
                Return ResourceManager.GetString("Asynchronous_cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Beep.
        '''</summary>
        Friend Shared ReadOnly Property Beep() As String
            Get
                Return ResourceManager.GetString("Beep", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Behavior.
        '''</summary>
        Friend Shared ReadOnly Property Behavior_cat() As String
            Get
                Return ResourceManager.GetString("Behavior_cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Browse....
        '''</summary>
        Friend Shared ReadOnly Property Browse() As String
            Get
                Return ResourceManager.GetString("Browse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Defines buttons displayed on message box.
        '''</summary>
        Friend Shared ReadOnly Property Buttons_d() As String
            Get
                Return ResourceManager.GetString("Buttons_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raised when file is changed.
        '''</summary>
        Friend Shared ReadOnly Property ChangedSync_d() As String
            Get
                Return ResourceManager.GetString("ChangedSync_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check boxes displayed for message box. Can be used for example for &apos;Do not show this message in future&apos; option..
        '''</summary>
        Friend Shared ReadOnly Property CheckBoxes_d() As String
            Get
                Return ResourceManager.GetString("CheckBoxes_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indicates of option is selected.
        '''</summary>
        Friend Shared ReadOnly Property Checked_d() As String
            Get
                Return ResourceManager.GetString("Checked_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raised when value of the Checked property changes.
        '''</summary>
        Friend Shared ReadOnly Property CheckedChanged_d() As String
            Get
                Return ResourceManager.GetString("CheckedChanged_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clear.
        '''</summary>
        Friend Shared ReadOnly Property Clear() As String
            Get
                Return ResourceManager.GetString("Clear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raised when user clicks the button. Can be canceled..
        '''</summary>
        Friend Shared ReadOnly Property ClickPreview_d() As String
            Get
                Return ResourceManager.GetString("ClickPreview_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raised after dialog is closed.
        '''</summary>
        Friend Shared ReadOnly Property Closed_d() As String
            Get
                Return ResourceManager.GetString("Closed_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Value returned by the Show function / DialogResult property when user closes the dialog by closing dialog window or by pressing escape.
        '''</summary>
        Friend Shared ReadOnly Property CloseResponse_d() As String
            Get
                Return ResourceManager.GetString("CloseResponse_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Colors.
        '''</summary>
        Friend Shared ReadOnly Property Colors_cat() As String
            Get
                Return ResourceManager.GetString("Colors_cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets sort column index. Set this property to value out of range of columns (e.g. -1) to avoid sorting..
        '''</summary>
        Friend Shared ReadOnly Property Column_d() As String
            Get
                Return ResourceManager.GetString("Column_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Combo box displayed on dialog.
        '''</summary>
        Friend Shared ReadOnly Property ComboBox_d() As String
            Get
                Return ResourceManager.GetString("ComboBox_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Config.
        '''</summary>
        Friend Shared ReadOnly Property Config_cat() As String
            Get
                Return ResourceManager.GetString("Config_cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raised when count-down time ticks - once a second..
        '''</summary>
        Friend Shared ReadOnly Property CountDown_d() As String
            Get
                Return ResourceManager.GetString("CountDown_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raised when file is created.
        '''</summary>
        Friend Shared ReadOnly Property CreatedSync_d() As String
            Get
                Return ResourceManager.GetString("CreatedSync_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data.
        '''</summary>
        Friend Shared ReadOnly Property Data_cat() As String
            Get
                Return ResourceManager.GetString("Data_cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DDE.
        '''</summary>
        Friend Shared ReadOnly Property DDE_cat() As String
            Get
                Return ResourceManager.GetString("DDE_cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Default.
        '''</summary>
        Friend Shared ReadOnly Property Default_cat() As String
            Get
                Return ResourceManager.GetString("Default_cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to indicates 0-based index of button that has focus when message box is shown and is default button for message box (usually reported when user presses enter)..
        '''</summary>
        Friend Shared ReadOnly Property DefaultButton_d() As String
            Get
                Return ResourceManager.GetString("DefaultButton_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raised when file is deleted.
        '''</summary>
        Friend Shared ReadOnly Property DeletedSync_d() As String
            Get
                Return ResourceManager.GetString("DeletedSync_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets if sorting order is reversed.
        '''</summary>
        Friend Shared ReadOnly Property Descending_d() As String
            Get
                Return ResourceManager.GetString("Descending_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Design.
        '''</summary>
        Friend Shared ReadOnly Property Design_cat() As String
            Get
                Return ResourceManager.GetString("Design_cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Display.
        '''</summary>
        Friend Shared ReadOnly Property Display_cat() As String
            Get
                Return ResourceManager.GetString("Display_cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indicates member (property, field) used to obtain text to be shown to user for each item..
        '''</summary>
        Friend Shared ReadOnly Property DisplayMember_d() As String
            Get
                Return ResourceManager.GetString("DisplayMember_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DragDrop.
        '''</summary>
        Friend Shared ReadOnly Property DragDrop_cat() As String
            Get
                Return ResourceManager.GetString("DragDrop_cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indicates if user can change text of combo box (true) or must select only form list of predefined values (false)..
        '''</summary>
        Friend Shared ReadOnly Property Editable_d() As String
            Get
                Return ResourceManager.GetString("Editable_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indicates if control is enabled, so user can interact with it..
        '''</summary>
        Friend Shared ReadOnly Property Enabled_d() As String
            Get
                Return ResourceManager.GetString("Enabled_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exclamation.
        '''</summary>
        Friend Shared ReadOnly Property Exclamation() As String
            Get
                Return ResourceManager.GetString("Exclamation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Focus.
        '''</summary>
        Friend Shared ReadOnly Property Focus_cat() As String
            Get
                Return ResourceManager.GetString("Focus_cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Folder Browsing.
        '''</summary>
        Friend Shared ReadOnly Property FolderBrowsing_cat() As String
            Get
                Return ResourceManager.GetString("FolderBrowsing_cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Font.
        '''</summary>
        Friend Shared ReadOnly Property Font_cat() As String
            Get
                Return ResourceManager.GetString("Font_cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Format.
        '''</summary>
        Friend Shared ReadOnly Property Format_cat() As String
            Get
                Return ResourceManager.GetString("Format_cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hand.
        '''</summary>
        Friend Shared ReadOnly Property Hand() As String
            Get
                Return ResourceManager.GetString("Hand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Icon shown in left to corner (lrt) of dialog.
        '''</summary>
        Friend Shared ReadOnly Property Icon_d() As String
            Get
                Return ResourceManager.GetString("Icon_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Images (bmp,jpeg,png,gif,tiff)|*.bmp;*.jpeg;*.jpg;*.gif;*.tif;*.tiff;*.png.
        '''</summary>
        Friend Shared ReadOnly Property ImagesFilter() As String
            Get
                Return ResourceManager.GetString("ImagesFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Items.
        '''</summary>
        Friend Shared ReadOnly Property Items_cat() As String
            Get
                Return ResourceManager.GetString("Items_cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Items shown to user in drop down. Item can be any Object..
        '''</summary>
        Friend Shared ReadOnly Property Items_d() As String
            Get
                Return ResourceManager.GetString("Items_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Key.
        '''</summary>
        Friend Shared ReadOnly Property Key_cat() As String
            Get
                Return ResourceManager.GetString("Key_cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Layout.
        '''</summary>
        Friend Shared ReadOnly Property Layout_cat() As String
            Get
                Return ResourceManager.GetString("Layout_cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to List.
        '''</summary>
        Friend Shared ReadOnly Property List_cat() As String
            Get
                Return ResourceManager.GetString("List_cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load from file....
        '''</summary>
        Friend Shared ReadOnly Property LoadFromFile() As String
            Get
                Return ResourceManager.GetString("LoadFromFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Text displayed on the control.
        '''</summary>
        Friend Shared ReadOnly Property MessageBoxButton_Text_d() As String
            Get
                Return ResourceManager.GetString("MessageBoxButton_Text_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} ({1:s}).
        '''</summary>
        Friend Shared ReadOnly Property MessageBoxCounDownTimeFormat() As String
            Get
                Return ResourceManager.GetString("MessageBoxCounDownTimeFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Misc.
        '''</summary>
        Friend Shared ReadOnly Property Misc_cat() As String
            Get
                Return ResourceManager.GetString("Misc_cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mouse.
        '''</summary>
        Friend Shared ReadOnly Property Mouse_cat() As String
            Get
                Return ResourceManager.GetString("Mouse_cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New ....
        '''</summary>
        Friend Shared ReadOnly Property New___() As String
            Get
                Return ResourceManager.GetString("New___", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Only SOI and EOI markers can have lenght set to zero, length 1 is not allowed.
        '''</summary>
        Friend Shared ReadOnly Property OnlySOIAndEOIMarkersCanHaveLenghtSetToZeroLength1IsNotAllowed() As String
            Get
                Return ResourceManager.GetString("OnlySOIAndEOIMarkersCanHaveLenghtSetToZeroLength1IsNotAllowed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Addtional options controlling how dialog is displayed.
        '''</summary>
        Friend Shared ReadOnly Property Options_d() As String
            Get
                Return ResourceManager.GetString("Options_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Play.
        '''</summary>
        Friend Shared ReadOnly Property Play() As String
            Get
                Return ResourceManager.GetString("Play", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sound to be played when message box is shown.
        '''</summary>
        Friend Shared ReadOnly Property PlayOnShow_d() As String
            Get
                Return ResourceManager.GetString("PlayOnShow_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Position.
        '''</summary>
        Friend Shared ReadOnly Property Position_cat() As String
            Get
                Return ResourceManager.GetString("Position_cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Private.
        '''</summary>
        Friend Shared ReadOnly Property Private_cat() As String
            Get
                Return ResourceManager.GetString("Private_cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Text of prompt displayed to the user..
        '''</summary>
        Friend Shared ReadOnly Property Prompt_d() As String
            Get
                Return ResourceManager.GetString("Prompt_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Property Changed.
        '''</summary>
        Friend Shared ReadOnly Property PropertyChanged_cat() As String
            Get
                Return ResourceManager.GetString("PropertyChanged_cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Question.
        '''</summary>
        Friend Shared ReadOnly Property Question() As String
            Get
                Return ResourceManager.GetString("Question", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Radio buttons (options) displayed on messagebox.
        '''</summary>
        Friend Shared ReadOnly Property Radios_d() As String
            Get
                Return ResourceManager.GetString("Radios_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raised when file is renamed.
        '''</summary>
        Friend Shared ReadOnly Property RenamedSync_d() As String
            Get
                Return ResourceManager.GetString("RenamedSync_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Result of message box returned when this button is clicked..
        '''</summary>
        Friend Shared ReadOnly Property Result_d() As String
            Get
                Return ResourceManager.GetString("Result_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save data as....
        '''</summary>
        Friend Shared ReadOnly Property SaveDataAs() As String
            Get
                Return ResourceManager.GetString("SaveDataAs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scale.
        '''</summary>
        Friend Shared ReadOnly Property Scale_cat() As String
            Get
                Return ResourceManager.GetString("Scale_cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indicates 0-based index of selected item in combo box..
        '''</summary>
        Friend Shared ReadOnly Property SelectedIndex_d() As String
            Get
                Return ResourceManager.GetString("SelectedIndex_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raised when value of the SelectedIndex property changes..
        '''</summary>
        Friend Shared ReadOnly Property SelectedIndexChanged_d() As String
            Get
                Return ResourceManager.GetString("SelectedIndexChanged_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raised when value of the SelectedItem property changes.
        '''</summary>
        Friend Shared ReadOnly Property SelectedItemChanged_d() As String
            Get
                Return ResourceManager.GetString("SelectedItemChanged_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select wav file.
        '''</summary>
        Friend Shared ReadOnly Property SelectWavFile() As String
            Get
                Return ResourceManager.GetString("SelectWavFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raised after dialog is shown.
        '''</summary>
        Friend Shared ReadOnly Property Shown_d() As String
            Get
                Return ResourceManager.GetString("Shown_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets the way of sorting.
        '''</summary>
        Friend Shared ReadOnly Property SortMode_d() As String
            Get
                Return ResourceManager.GetString("SortMode_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current check state of check box.
        '''</summary>
        Friend Shared ReadOnly Property State_d() As String
            Get
                Return ResourceManager.GetString("State_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raised ehrn value of the State property changed.
        '''</summary>
        Friend Shared ReadOnly Property StateChanged_d() As String
            Get
                Return ResourceManager.GetString("StateChanged_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Text.
        '''</summary>
        Friend Shared ReadOnly Property Text_cat() As String
            Get
                Return ResourceManager.GetString("Text_cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indicateis if checkbox has 3rd intermediate state.
        '''</summary>
        Friend Shared ReadOnly Property ThreeState_d() As String
            Get
                Return ResourceManager.GetString("ThreeState_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indicates 0-based index of button which displays the count-down timer. It aslo defines result of dialog returned when time elapses. -1 chose button automatically acording to CloseResponse, &lt;-1 displays count-down in title, &gt; number of buttons hides count-down indicator..
        '''</summary>
        Friend Shared ReadOnly Property TimeButton_d() As String
            Get
                Return ResourceManager.GetString("TimeButton_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inidcates how long the message box will be show to user before being closed automatically. If zero or less, no count-down takes effect..
        '''</summary>
        Friend Shared ReadOnly Property Timer_d() As String
            Get
                Return ResourceManager.GetString("Timer_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Title shown in dialog header.
        '''</summary>
        Friend Shared ReadOnly Property Title_d() As String
            Get
                Return ResourceManager.GetString("Title_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tool tip text (help) for control.
        '''</summary>
        Friend Shared ReadOnly Property ToolTip_d() As String
            Get
                Return ResourceManager.GetString("ToolTip_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to wav files (*.wav)|*.wav.
        '''</summary>
        Friend Shared ReadOnly Property WavFilter() As String
            Get
                Return ResourceManager.GetString("WavFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Window Style.
        '''</summary>
        Friend Shared ReadOnly Property WindowStyle_cat() As String
            Get
                Return ResourceManager.GetString("WindowStyle_cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Defines fill width applicable when SortMode is ZeroFill. Items will be filled with zeros (&quot;0&quot;) to specified width and then sorted as strings..
        '''</summary>
        Friend Shared ReadOnly Property ZerofillWidth_d() As String
            Get
                Return ResourceManager.GetString("ZerofillWidth_d", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
