'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3031
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace WindowsT.FormsT
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class DerivedControls
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Tools.DerivedControls", GetType(DerivedControls).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets a value indicating whether the control is automatically resized to display its entire contents..
        '''</summary>
        Friend Shared ReadOnly Property AutoSize_d() As String
            Get
                Return ResourceManager.GetString("AutoSize_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Get or sets value indicating if text automatically displays value of progress bar.
        '''</summary>
        Friend Shared ReadOnly Property AutoText_d() As String
            Get
                Return ResourceManager.GetString("AutoText_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ocuurs when AutoText changes.
        '''</summary>
        Friend Shared ReadOnly Property AutoTextChanged_d() As String
            Get
                Return ResourceManager.GetString("AutoTextChanged_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Format string used to format value when displayed as text of control automatically..
        '''</summary>
        Friend Shared ReadOnly Property AutoTextFormat_d() As String
            Get
                Return ResourceManager.GetString("AutoTextFormat_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ocuurs when AutoTextFormat changes.
        '''</summary>
        Friend Shared ReadOnly Property AutoTextFormatChanged_d() As String
            Get
                Return ResourceManager.GetString("AutoTextFormatChanged_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fired when BindingContextChanged of internal ComboBox occurs.
        '''</summary>
        Friend Shared ReadOnly Property BindingContextChanged_d() As String
            Get
                Return ResourceManager.GetString("BindingContextChanged_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets the data bindings for the control..
        '''</summary>
        Friend Shared ReadOnly Property DataBindings_d() As String
            Get
                Return ResourceManager.GetString("DataBindings_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets the data source for internal ComboBox.
        '''</summary>
        Friend Shared ReadOnly Property DataSource_d() As String
            Get
                Return ResourceManager.GetString("DataSource_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stores value for the Link.Description of Link that represents this LinkItem.
        '''</summary>
        Friend Shared ReadOnly Property Description_d() As String
            Get
                Return ResourceManager.GetString("Description_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets the property to display for internal ComboBox..
        '''</summary>
        Friend Shared ReadOnly Property DisplayMember_d() As String
            Get
                Return ResourceManager.GetString("DisplayMember_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stores value for the Link.Enabled of Link that represents this LinkItem.
        '''</summary>
        Friend Shared ReadOnly Property Enabled_d() As String
            Get
                Return ResourceManager.GetString("Enabled_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets a value indicating whether the form will receive key events before the event is passed to the control that has focus..
        '''</summary>
        Friend Shared ReadOnly Property KeyPreview_d() As String
            Get
                Return ResourceManager.GetString("KeyPreview_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contains default value of the KeyPreview property..
        '''</summary>
        Friend Shared ReadOnly Property KeyPreviewDefaultValue_d() As String
            Get
                Return ResourceManager.GetString("KeyPreviewDefaultValue_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data associated with this link.
        '''</summary>
        Friend Shared ReadOnly Property LinkData_d() As String
            Get
                Return ResourceManager.GetString("LinkData_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Path (string representation of URI) of target of the link.
        '''</summary>
        Friend Shared ReadOnly Property LinkPath_d() As String
            Get
                Return ResourceManager.GetString("LinkPath_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to URI of target of the link.
        '''</summary>
        Friend Shared ReadOnly Property LinkURI_d() As String
            Get
                Return ResourceManager.GetString("LinkURI_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to List of all items in label.
        '''</summary>
        Friend Shared ReadOnly Property ListOfAllItemsInLabel() As String
            Get
                Return ResourceManager.GetString("ListOfAllItemsInLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stores value for the Link.Name of Link that represents this LinkItem.
        '''</summary>
        Friend Shared ReadOnly Property Name_d() As String
            Get
                Return ResourceManager.GetString("Name_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stores value for the Link.Tag of Link that represents this LinkItem.
        '''</summary>
        Friend Shared ReadOnly Property Tag_d() As String
            Get
                Return ResourceManager.GetString("Tag_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Text to be show in place of this item.
        '''</summary>
        Friend Shared ReadOnly Property Text_LinkLabelItem_d() As String
            Get
                Return ResourceManager.GetString("Text_LinkLabelItem_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets the alignment of text in the label..
        '''</summary>
        Friend Shared ReadOnly Property TextAlign_d() As String
            Get
                Return ResourceManager.GetString("TextAlign_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Occurs when Value changes.
        '''</summary>
        Friend Shared ReadOnly Property ValueChanged_d() As String
            Get
                Return ResourceManager.GetString("ValueChanged_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets the property to use as the actual value for the items in internal ComboBox..
        '''</summary>
        Friend Shared ReadOnly Property ValueMember_d() As String
            Get
                Return ResourceManager.GetString("ValueMember_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stores value for the Link.Visited of Link that represents this LinkItem.
        '''</summary>
        Friend Shared ReadOnly Property Visited_d() As String
            Get
                Return ResourceManager.GetString("Visited_d", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
