'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3031
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace WindowsT.FormsT
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class CompositeControls
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Tools.CompositeControls", GetType(CompositeControls).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raised after Add menu item is clicked.
        '''</summary>
        Friend Shared ReadOnly Property Add_d() As String
            Get
                Return ResourceManager.GetString("Add_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to State of the Add menu item.
        '''</summary>
        Friend Shared ReadOnly Property AddMenuState_d() As String
            Get
                Return ResourceManager.GetString("AddMenuState_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets value indicating if Status.Status automatically changes when keyword is added or removed.
        '''</summary>
        Friend Shared ReadOnly Property AutoChange_d() As String
            Get
                Return ResourceManager.GetString("AutoChange_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets value indicating if Status automatically changes to Statuses.Changed when tmiMarkAsChanged is clicked.
        '''</summary>
        Friend Shared ReadOnly Property AutoChanged_d() As String
            Get
                Return ResourceManager.GetString("AutoChanged_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name of per-session cache of keywords used by this instance.
        '''</summary>
        Friend Shared ReadOnly Property AutoCompleteCacheName_d() As String
            Get
                Return ResourceManager.GetString("AutoCompleteCacheName_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indicates if editor uses automatically shared lists of keywords and synonyms (among instances with same AutoCompleteCacheName) or not..
        '''</summary>
        Friend Shared ReadOnly Property AutomaticLists_d() As String
            Get
                Return ResourceManager.GetString("AutomaticLists_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Base Types.
        '''</summary>
        Friend Shared ReadOnly Property BaseTypes() As String
            Get
                Return ResourceManager.GetString("BaseTypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indicates if dialog supports cancelation..
        '''</summary>
        Friend Shared ReadOnly Property CanCancel_d() As String
            Get
                Return ResourceManager.GetString("CanCancel_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets value idicating if keywords are case sensitive.
        '''</summary>
        Friend Shared ReadOnly Property CaseSensitive_d() As String
            Get
                Return ResourceManager.GetString("CaseSensitive_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Changed.
        '''</summary>
        Friend Shared ReadOnly Property Changed() As String
            Get
                Return ResourceManager.GetString("Changed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indicates if form automatically closes when BackgroundWorker finishes its work..
        '''</summary>
        Friend Shared ReadOnly Property CloseOnFinish_d() As String
            Get
                Return ResourceManager.GetString("CloseOnFinish_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets text of ColumnHeader which displays CodePage of encoding. Applicable only when Style is ListView.
        '''</summary>
        Friend Shared ReadOnly Property CodePageColumnHeaderText_d() As String
            Get
                Return ResourceManager.GetString("CodePageColumnHeaderText_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Defines width of ColumnHeader which displays CodePage of encoding. Applicable only when Style is ListView.
        '''</summary>
        Friend Shared ReadOnly Property CodePageColumnHeaderWidht_d() As String
            Get
                Return ResourceManager.GetString("CodePageColumnHeaderWidht_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets order of columns of ListView when Style is ListView.
        '''</summary>
        Friend Shared ReadOnly Property ColumnOrder_d() As String
            Get
                Return ResourceManager.GetString("ColumnOrder_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raised after Delete menu item is clicked.
        '''</summary>
        Friend Shared ReadOnly Property Delete_d() As String
            Get
                Return ResourceManager.GetString("Delete_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Deleted.
        '''</summary>
        Friend Shared ReadOnly Property Deleted() As String
            Get
                Return ResourceManager.GetString("Deleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to State of the Delete menu item.
        '''</summary>
        Friend Shared ReadOnly Property DeleteMenuState_d() As String
            Get
                Return ResourceManager.GetString("DeleteMenuState_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets text of ColumnHeader which displays DisplayName of encoding. Applicable only when Style is ListView.
        '''</summary>
        Friend Shared ReadOnly Property DisplayNameColumnHeaderText_d() As String
            Get
                Return ResourceManager.GetString("DisplayNameColumnHeaderText_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Defines width of ColumnHeader which displays DisplayName of encoding. Applicable only when Style is ListView.
        '''</summary>
        Friend Shared ReadOnly Property DisplayNameColumnHeaderWidth_d() As String
            Get
                Return ResourceManager.GetString("DisplayNameColumnHeaderWidth_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets format string used to display name of encodings in list.
        '''{0} is replaced by user friendly encoding name, {1} is replaced with IANA-registered name and {2} is replaced with code page number.
        '''</summary>
        Friend Shared ReadOnly Property DisplayStype_d() As String
            Get
                Return ResourceManager.GetString("DisplayStype_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to When true form will automatically start BackgroundWorker whne the Shown events occurs..
        '''</summary>
        Friend Shared ReadOnly Property DoWorkOnShow_d() As String
            Get
                Return ResourceManager.GetString("DoWorkOnShow_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Informative text displayed below the progress bar.
        '''</summary>
        Friend Shared ReadOnly Property Information_d() As String
            Get
                Return ResourceManager.GetString("Information_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raised when Style is ListView or ListBox and user double clicks some item or raised when item is selected and user presses the enter key not depending on Style..
        '''</summary>
        Friend Shared ReadOnly Property ItemDoubleClick_d() As String
            Get
                Return ResourceManager.GetString("ItemDoubleClick_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raised after user manually removes keyword(s).
        '''</summary>
        Friend Shared ReadOnly Property KeyWordRemoved_d() As String
            Get
                Return ResourceManager.GetString("KeyWordRemoved_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raised after Mark-as-changed menu item is clicked.
        '''</summary>
        Friend Shared ReadOnly Property MarkAsChanged_d() As String
            Get
                Return ResourceManager.GetString("MarkAsChanged_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to State of the Mark-as-changed menu item.
        '''</summary>
        Friend Shared ReadOnly Property MarkAsChangedMenuState_d() As String
            Get
                Return ResourceManager.GetString("MarkAsChangedMenuState_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets value indicating if merge button is checked (orange) or not (gray).
        '''</summary>
        Friend Shared ReadOnly Property Merge_d() As String
            Get
                Return ResourceManager.GetString("Merge_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets state of merge button.
        '''</summary>
        Friend Shared ReadOnly Property MergeButtonState_d() As String
            Get
                Return ResourceManager.GetString("MergeButtonState_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raised after value of the Merge property changed.
        '''</summary>
        Friend Shared ReadOnly Property MergeChanged_d() As String
            Get
                Return ResourceManager.GetString("MergeChanged_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to N/A.
        '''</summary>
        Friend Shared ReadOnly Property NA() As String
            Get
                Return ResourceManager.GetString("NA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets text of ColumnHeader which displays Name of encoding. Applicable only when Style is ListView.
        '''</summary>
        Friend Shared ReadOnly Property NameColumnHeaderText_d() As String
            Get
                Return ResourceManager.GetString("NameColumnHeaderText_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Defines width of ColumnHeader which displays Name of encoding. Applicable only when Style is ListView.
        '''</summary>
        Friend Shared ReadOnly Property NameColumnHeaderWidth_d() As String
            Get
                Return ResourceManager.GetString("NameColumnHeaderWidth_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New.
        '''</summary>
        Friend Shared ReadOnly Property New_() As String
            Get
                Return ResourceManager.GetString("New_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Normal.
        '''</summary>
        Friend Shared ReadOnly Property Normal() As String
            Get
                Return ResourceManager.GetString("Normal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Null.
        '''</summary>
        Friend Shared ReadOnly Property Null() As String
            Get
                Return ResourceManager.GetString("Null", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to List of assemblies or any other objects listed at top-level of tree-view.
        '''</summary>
        Friend Shared ReadOnly Property Objects_d() As String
            Get
                Return ResourceManager.GetString("Objects_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please wait....
        '''</summary>
        Friend Shared ReadOnly Property PleaseWait() As String
            Get
                Return ResourceManager.GetString("PleaseWait", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Style of ProgressBar that shows progresss.
        '''</summary>
        Friend Shared ReadOnly Property ProgressBarStyle_d() As String
            Get
                Return ResourceManager.GetString("ProgressBarStyle_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Information text displayed in upper part of form.
        '''</summary>
        Friend Shared ReadOnly Property Prompt_d() As String
            Get
                Return ResourceManager.GetString("Prompt_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to References.
        '''</summary>
        Friend Shared ReadOnly Property References() As String
            Get
                Return ResourceManager.GetString("References", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raised after Reset menu item is clicked.
        '''</summary>
        Friend Shared ReadOnly Property Reset_d() As String
            Get
                Return ResourceManager.GetString("Reset_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to State of the Reset menu item.
        '''</summary>
        Friend Shared ReadOnly Property ResetMenuState_d() As String
            Get
                Return ResourceManager.GetString("ResetMenuState_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets code page identifier of selected encoding or tries to select encoding with given code page.
        '''</summary>
        Friend Shared ReadOnly Property SelectedCodePage_d() As String
            Get
                Return ResourceManager.GetString("SelectedCodePage_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raised after the SelectedIndex property is changed.
        '''</summary>
        Friend Shared ReadOnly Property SelectedIndexChanged_d() As String
            Get
                Return ResourceManager.GetString("SelectedIndexChanged_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets The Internet Assigned Numbers Authority (IANA) name of selected encoding or tries to select encoding with given name.
        '''</summary>
        Friend Shared ReadOnly Property SelectedName_d() As String
            Get
                Return ResourceManager.GetString("SelectedName_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets value indicating if base types are shown..
        '''</summary>
        Friend Shared ReadOnly Property ShowBaseTypes_d() As String
            Get
                Return ResourceManager.GetString("ShowBaseTypes_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raised after property that controls which members are displayed in ListView was changed..
        '''</summary>
        Friend Shared ReadOnly Property ShowChanged_d() As String
            Get
                Return ResourceManager.GetString("ShowChanged_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets value indicating if CTors are shown..
        '''</summary>
        Friend Shared ReadOnly Property ShowCTors_d() As String
            Get
                Return ResourceManager.GetString("ShowCTors_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets value indicating if Events are shown..
        '''</summary>
        Friend Shared ReadOnly Property ShowEvents_d() As String
            Get
                Return ResourceManager.GetString("ShowEvents_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets value indicating if Fields are shown..
        '''</summary>
        Friend Shared ReadOnly Property ShowFields_d() As String
            Get
                Return ResourceManager.GetString("ShowFields_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets value indicating if namespaces are shown flat (true) or hierarchically (false)..
        '''</summary>
        Friend Shared ReadOnly Property ShowFlatNamespaces_d() As String
            Get
                Return ResourceManager.GetString("ShowFlatNamespaces_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets value indicating if generic arguments (type parameters) are shown..
        '''</summary>
        Friend Shared ReadOnly Property ShowGenericArguments_d() As String
            Get
                Return ResourceManager.GetString("ShowGenericArguments_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets value indicating if Global members (parts of properties and events) are shown..
        '''</summary>
        Friend Shared ReadOnly Property ShowGlobalMembers_d() As String
            Get
                Return ResourceManager.GetString("ShowGlobalMembers_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets value indicating if inherited members are shown..
        '''</summary>
        Friend Shared ReadOnly Property ShowInheritedMembers_d() As String
            Get
                Return ResourceManager.GetString("ShowInheritedMembers_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets value indicating if Initializers are shown..
        '''</summary>
        Friend Shared ReadOnly Property ShowInitializers_d() As String
            Get
                Return ResourceManager.GetString("ShowInitializers_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets value indicating if instance members are shown..
        '''</summary>
        Friend Shared ReadOnly Property ShowInstanceMembers_d() As String
            Get
                Return ResourceManager.GetString("ShowInstanceMembers_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets value indicating if Internal members are shown..
        '''</summary>
        Friend Shared ReadOnly Property ShowInternalMembers_d() As String
            Get
                Return ResourceManager.GetString("ShowInternalMembers_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets value indicating if Methods are shown..
        '''</summary>
        Friend Shared ReadOnly Property ShowMethods_d() As String
            Get
                Return ResourceManager.GetString("ShowMethods_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets value indicating if nested types are shown..
        '''</summary>
        Friend Shared ReadOnly Property ShowNestedTypes_d() As String
            Get
                Return ResourceManager.GetString("ShowNestedTypes_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets value indicating if private members are shown..
        '''</summary>
        Friend Shared ReadOnly Property ShowPrivateMembers_d() As String
            Get
                Return ResourceManager.GetString("ShowPrivateMembers_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets value indicating if properties are shown..
        '''</summary>
        Friend Shared ReadOnly Property ShowProperties_d() As String
            Get
                Return ResourceManager.GetString("ShowProperties_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets value indicating if Protected members are shown..
        '''</summary>
        Friend Shared ReadOnly Property ShowProtectedMembers_d() As String
            Get
                Return ResourceManager.GetString("ShowProtectedMembers_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets value indicating if references are shown..
        '''</summary>
        Friend Shared ReadOnly Property ShowReferences_d() As String
            Get
                Return ResourceManager.GetString("ShowReferences_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets value indicating if Show menu is shown..
        '''</summary>
        Friend Shared ReadOnly Property ShowShowMenu_d() As String
            Get
                Return ResourceManager.GetString("ShowShowMenu_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets value indicating if special members (parts of properties and events) are shown..
        '''</summary>
        Friend Shared ReadOnly Property ShowSpecialMembers_d() As String
            Get
                Return ResourceManager.GetString("ShowSpecialMembers_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets value indicating if static members are shown..
        '''</summary>
        Friend Shared ReadOnly Property ShowStaticMembers_d() As String
            Get
                Return ResourceManager.GetString("ShowStaticMembers_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets value indicating if the toolbar is shown..
        '''</summary>
        Friend Shared ReadOnly Property ShowToolbar_d() As String
            Get
                Return ResourceManager.GetString("ShowToolbar_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Specifies column and order of sorting. Applies only when Style is ListBox..
        '''</summary>
        Friend Shared ReadOnly Property Sorting_d() As String
            Get
                Return ResourceManager.GetString("Sorting_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to StatusMarker present on this control.
        '''</summary>
        Friend Shared ReadOnly Property Status_d() As String
            Get
                Return ResourceManager.GetString("Status_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raised after the Status property changes.
        '''</summary>
        Friend Shared ReadOnly Property StatusChanged_d() As String
            Get
                Return ResourceManager.GetString("StatusChanged_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shown status of control.
        '''</summary>
        Friend Shared ReadOnly Property StatusMarkerStatus_d() As String
            Get
                Return ResourceManager.GetString("StatusMarkerStatus_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets state of Status.
        '''</summary>
        Friend Shared ReadOnly Property StatusState_d() As String
            Get
                Return ResourceManager.GetString("StatusState_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Defines control used for showing encodings.
        '''</summary>
        Friend Shared ReadOnly Property Style_d() As String
            Get
                Return ResourceManager.GetString("Style_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets state of thesaurus button.
        '''</summary>
        Friend Shared ReadOnly Property ThesaurusButtonAttribute_d() As String
            Get
                Return ResourceManager.GetString("ThesaurusButtonAttribute_d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Argument passed to RunWorkerAsync method when DoWorkOnShow is true..
        '''</summary>
        Friend Shared ReadOnly Property WorkerArgument_d() As String
            Get
                Return ResourceManager.GetString("WorkerArgument_d", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
