//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tools.VisualStudioT.GeneratorsT.ResXFileGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tools.VisualStudioT.GeneratorsT.ResXFileGenerator.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create the format method named &apos;{0}&apos; for the resource key &apos;{1}&apos;..
        /// </summary>
        internal static string CannotCreateFormatMethod {
            get {
                return ResourceManager.GetString("CannotCreateFormatMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create property for resource named &apos;{0}&apos;..
        /// </summary>
        internal static string CannotCreatePropertyForResource {
            get {
                return ResourceManager.GetString("CannotCreatePropertyForResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This class was auto-generated by the StronglyTypedResourceBuilderEx class via the {0} custom tool..
        /// </summary>
        internal static string ClassComments1Format {
            get {
                return ResourceManager.GetString("ClassComments1Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add or remove a member, edit your .ResX file then rerun the {0} custom tool or rebuild your VS.NET project..
        /// </summary>
        internal static string ClassComments2Format {
            get {
                return ResourceManager.GetString("ClassComments2Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © Dmytro Kryvko 2006-{0} (http://dmytro.kryvko.googlepages.com/); Đonny 2008-{0} (http://tools.codeplex.com).
        /// </summary>
        internal static string ClassCommentsCopyright {
            get {
                return ResourceManager.GetString("ClassCommentsCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A strongly-typed resource class, for looking up localized strings, formatting them, etc..
        /// </summary>
        internal static string ClassDocComment {
            get {
                return ResourceManager.GetString("ClassDocComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overrides the current thread&apos;s CurrentUICulture property for all.
        /// </summary>
        internal static string CulturePropertyComment1 {
            get {
                return ResourceManager.GetString("CulturePropertyComment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resource lookups using this strongly typed resource class..
        /// </summary>
        internal static string CulturePropertyComment2 {
            get {
                return ResourceManager.GetString("CulturePropertyComment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Property name: {1}..
        /// </summary>
        internal static string ErrorInFormatPropertyForResource {
            get {
                return ResourceManager.GetString("ErrorInFormatPropertyForResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formats a localized string similar to &apos;{0}&apos;..
        /// </summary>
        internal static string FormatMethodComment {
            get {
                return ResourceManager.GetString("FormatMethodComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stub formatting method returning the {0} property value..
        /// </summary>
        internal static string FormatStubMethodComment {
            get {
                return ResourceManager.GetString("FormatStubMethodComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread safe lock object used by this class..
        /// </summary>
        internal static string InternalSyncObjectPropertyComment {
            get {
                return ResourceManager.GetString("InternalSyncObjectPropertyComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string InvalidIdentifier {
            get {
                return ResourceManager.GetString("InvalidIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;returns&gt;A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.&lt;/returns&gt;.
        /// </summary>
        internal static string MethodReturnValueComment {
            get {
                return ResourceManager.GetString("MethodReturnValueComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When passing ResXDataNodes as the IDictionary values to StronglyTypedResourceBuilderEx.Create, the keys must match the corresponding values for ResXDataNode.Name.  Key name: &apos;{0}&apos;, ResXDataNode.Name: &apos;{1}&apos;..
        /// </summary>
        internal static string MismatchedResourceName {
            get {
                return ResourceManager.GetString("MismatchedResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks up a resource &apos;{0}&apos;..
        /// </summary>
        internal static string NonStringPropertyComment {
            get {
                return ResourceManager.GetString("NonStringPropertyComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;param name=&quot;arg{0}&quot;&gt;An object ({0}) to format.&lt;/param&gt;.
        /// </summary>
        internal static string ParamCommentStatement {
            get {
                return ResourceManager.GetString("ParamCommentStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the cached ResourceManager instance used by this class..
        /// </summary>
        internal static string ResMgrPropertyComment {
            get {
                return ResourceManager.GetString("ResMgrPropertyComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks up a localized string similar to &apos;{0}&apos;..
        /// </summary>
        internal static string StringPropertyComment {
            get {
                return ResourceManager.GetString("StringPropertyComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringTruncatedComment {
            get {
                return ResourceManager.GetString("StringTruncatedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;returns&gt;The {0} property value.&lt;/returns&gt;.
        /// </summary>
        internal static string StubMethodReturnValueComment {
            get {
                return ResourceManager.GetString("StubMethodReturnValueComment", resourceCulture);
            }
        }
    }
}
