'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.208
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Tools.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Základní.
        '''</summary>
        Friend ReadOnly Property cat_Basic() As String
            Get
                Return ResourceManager.GetString("cat_Basic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DataSet.
        '''</summary>
        Friend ReadOnly Property cat_Dataset() As String
            Get
                Return ResourceManager.GetString("cat_Dataset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vyplňování.
        '''</summary>
        Friend ReadOnly Property cat_Filling() As String
            Get
                Return ResourceManager.GetString("cat_Filling", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Formát.
        '''</summary>
        Friend ReadOnly Property cat_Format() As String
            Get
                Return ResourceManager.GetString("cat_Format", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Formátování.
        '''</summary>
        Friend ReadOnly Property cat_Formatting() As String
            Get
                Return ResourceManager.GetString("cat_Formatting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Umístění.
        '''</summary>
        Friend ReadOnly Property cat_Location() As String
            Get
                Return ResourceManager.GetString("cat_Location", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Postprocesing.
        '''</summary>
        Friend ReadOnly Property cat_PostProcessing() As String
            Get
                Return ResourceManager.GetString("cat_PostProcessing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opakování.
        '''</summary>
        Friend ReadOnly Property cat_Repeat() As String
            Get
                Return ResourceManager.GetString("cat_Repeat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Speciální případy.
        '''</summary>
        Friend ReadOnly Property cat_SpecialCases() As String
            Get
                Return ResourceManager.GetString("cat_SpecialCases", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Šablona.
        '''</summary>
        Friend ReadOnly Property cat_Template() As String
            Get
                Return ResourceManager.GetString("cat_Template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to XML.
        '''</summary>
        Friend ReadOnly Property cat_Xml() As String
            Get
                Return ResourceManager.GetString("cat_Xml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Povolí XSLT funkci document().
        '''</summary>
        Friend ReadOnly Property d_AllowDocumentFunction() As String
            Get
                Return ResourceManager.GetString("d_AllowDocumentFunction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Povolit vložený kód v XSL šabloně..
        '''</summary>
        Friend ReadOnly Property d_AllowScript() As String
            Get
                Return ResourceManager.GetString("d_AllowScript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Název sloupce, který bude použit pro rozložení výstupu tabulky na jednotlivé listy. Pokaždé, když se hodnota v tomto sloupci změní, je založen nový list. Case-sensitive..
        '''</summary>
        Friend ReadOnly Property d_BreakColumn() As String
            Get
                Return ResourceManager.GetString("d_BreakColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1-based index sloupce (v Excelu) od nějž budou sloupce kopírovány (levý do pravého). 0 - nebudou kopírovány vůbec..
        '''</summary>
        Friend ReadOnly Property d_CopyColumnsFrom() As String
            Get
                Return ResourceManager.GetString("d_CopyColumnsFrom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kultura použitá pro formátování dat a čísel. Například en-US, cs-CZ. Prázdné - použijete invariantní kultura..
        '''</summary>
        Friend ReadOnly Property d_Culture() As String
            Get
                Return ResourceManager.GetString("d_Culture", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Název DataSetu - bude použit jako název kořenového elementu v XML..
        '''</summary>
        Friend ReadOnly Property d_DataSetName() As String
            Get
                Return ResourceManager.GetString("d_DataSetName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to URI jmenného prostoru XML pro DataSet.
        '''</summary>
        Friend ReadOnly Property d_DatasetNamespace() As String
            Get
                Return ResourceManager.GetString("d_DatasetNamespace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Název tabulky - bude použit jako název XML elementu..
        '''</summary>
        Friend ReadOnly Property d_datasetTableName() As String
            Get
                Return ResourceManager.GetString("d_datasetTableName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Formát pro formátování sloupců typu datum/čas. Použijte .NET formát. Prázdné - výchozí. Závisí na kultuře..
        '''</summary>
        Friend ReadOnly Property d_DateFormat() As String
            Get
                Return ResourceManager.GetString("d_DateFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zapsat názvy sloupců z databáze do zápatí?.
        '''</summary>
        Friend ReadOnly Property d_Footer() As String
            Get
                Return ResourceManager.GetString("d_Footer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zapsat názvy sloupců z databáze do záhlaví?.
        '''</summary>
        Friend ReadOnly Property d_Header() As String
            Get
                Return ResourceManager.GetString("d_Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pokud je načítán soubor šablony identifikuje kolik prvních řádků přijde do záhlaví, zbytek přijde do zápatí..
        '''</summary>
        Friend ReadOnly Property d_HeaderSize() As String
            Get
                Return ResourceManager.GetString("d_HeaderSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sloupec, podle něhož bude nastaven název listu. Prázdné - název lsitu se nezmění..
        '''</summary>
        Friend ReadOnly Property d_NameColumn() As String
            Get
                Return ResourceManager.GetString("d_NameColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sloupec obsahující názvy listů, case-sensitive..
        '''</summary>
        Friend ReadOnly Property d_NameColumnXlsRepeat() As String
            Get
                Return ResourceManager.GetString("d_NameColumnXlsRepeat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Formátovací řetězec jímž bude formátován název listu. {0} bude nahrazena názvem listu..
        '''</summary>
        Friend ReadOnly Property d_NameFormat() As String
            Get
                Return ResourceManager.GetString("d_NameFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nový řádek.
        '''</summary>
        Friend ReadOnly Property d_NewLine() As String
            Get
                Return ResourceManager.GetString("d_NewLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jak se zachovat, pokud hodnota obsahuje konec řádku. Je možno nahrazovat konce řádků, jen z Nový řádek nebo všechny podle Unicode..
        '''</summary>
        Friend ReadOnly Property d_NlEscape() As String
            Get
                Return ResourceManager.GetString("d_NlEscape", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Řetězec je vložen místo NULL hodnoty..
        '''</summary>
        Friend ReadOnly Property d_NullValue() As String
            Get
                Return ResourceManager.GetString("d_NullValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Formát pro formátování sloupců typu číslo. Použijte .NET formát. Prázdné - výchozí. Závisí na kultuře..
        '''</summary>
        Friend ReadOnly Property d_NumberFormat() As String
            Get
                Return ResourceManager.GetString("d_NumberFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VB.NET kód, kerý je spuštěn po exportu. Kód je zavřen do funkce, které je předán parametr WorkBook..
        '''</summary>
        Friend ReadOnly Property d_PostProcessingCode() As String
            Get
                Return ResourceManager.GetString("d_PostProcessingCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Spustit makro se zadaným názvem po dokončení exportu. Pozor: Makro nemusí fungovat v závislosti na nastavení Excelu!.
        '''</summary>
        Friend ReadOnly Property d_RunMacroAfter() As String
            Get
                Return ResourceManager.GetString("d_RunMacroAfter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Název nebo index (1-based) listu, který bude vybrán po doběhnutí exportu. Ignorováno u subreportů. Prázdné - aktivní list nebude změněn..
        '''</summary>
        Friend ReadOnly Property d_SelectList() As String
            Get
                Return ResourceManager.GetString("d_SelectList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Oddělovač sloupců Např. , ; | nebo tabulátor (vložte zkopírováním z Notepadu).
        '''</summary>
        Friend ReadOnly Property d_Separator() As String
            Get
                Return ResourceManager.GetString("d_Separator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Čárkou oddělený seznam názvů sloupců (z databáze)., které budou vynechány při výpisu do Excelu. Pokud se z nějakých exotických důvodů vyskytuje v názvu sloupce čárka (,) nahraďte ji pipou (|); pipu (|) nahraďte dvěma (||). Case-sinsitive..
        '''</summary>
        Friend ReadOnly Property d_SkipColumns() As String
            Get
                Return ResourceManager.GetString("d_SkipColumns", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Speciální řetězec, pokud má být konec řádku nahrazen speciálním řetězcem. Speciální řetězec je, pokud se vyskytne v hodnotě, escapován stejným stylem jako textový kvalifikátor..
        '''</summary>
        Friend ReadOnly Property d_SpecialString() As String
            Get
                Return ResourceManager.GetString("d_SpecialString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pozastavit přepočítávání vzorců během vyplňování listu? (urychlí operaci).
        '''</summary>
        Friend ReadOnly Property d_SuspendRecalculations() As String
            Get
                Return ResourceManager.GetString("d_SuspendRecalculations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ohraničuje textová pole z obou stran. Použije se pokud pole obsahuje divoké znaky nebo je to vyžadováno nastavením. Např.: &quot;, &apos;.
        '''</summary>
        Friend ReadOnly Property d_TextQualifier() As String
            Get
                Return ResourceManager.GetString("d_TextQualifier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Určuje jak bude zacházeno s řetězcem, který obsahuje textový kvalifikátor..
        '''</summary>
        Friend ReadOnly Property d_TextQualifierEscape() As String
            Get
                Return ResourceManager.GetString("d_TextQualifierEscape", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Určuje jestli textový klavlifikátor bude použit jen pokud je potřeba, vždy nebo vždy na řetězcové sloupce a je pokud je potřeba na data a čísla..
        '''</summary>
        Friend ReadOnly Property d_TextQualifierUsage() As String
            Get
                Return ResourceManager.GetString("d_TextQualifierUsage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Má být hodnota z rozkladového sloupce zapisována do listu?.
        '''</summary>
        Friend ReadOnly Property d_WriteBreak() As String
            Get
                Return ResourceManager.GetString("d_WriteBreak", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Má být hodnota ze sloupce názvu zapisována do listu?.
        '''</summary>
        Friend ReadOnly Property d_WriteName() As String
            Get
                Return ResourceManager.GetString("d_WriteName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prefix jmenného prostoru DataSetu.
        '''</summary>
        Friend ReadOnly Property d_XmlPrefix() As String
            Get
                Return ResourceManager.GetString("d_XmlPrefix", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Povolit funkci Document().
        '''</summary>
        Friend ReadOnly Property dn_AllowDocumentFunction() As String
            Get
                Return ResourceManager.GetString("dn_AllowDocumentFunction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Povolit script.
        '''</summary>
        Friend ReadOnly Property dn_AllowScript() As String
            Get
                Return ResourceManager.GetString("dn_AllowScript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Auto-šířka sloupců.
        '''</summary>
        Friend ReadOnly Property dn_AutoWidtn() As String
            Get
                Return ResourceManager.GetString("dn_AutoWidtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rozložit podle.
        '''</summary>
        Friend ReadOnly Property dn_BreakColumn() As String
            Get
                Return ResourceManager.GetString("dn_BreakColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sloupec 1.
        '''</summary>
        Friend ReadOnly Property dn_Col1() As String
            Get
                Return ResourceManager.GetString("dn_Col1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Řádek názvu.
        '''</summary>
        Friend ReadOnly Property dn_ColumnNameRow() As String
            Get
                Return ResourceManager.GetString("dn_ColumnNameRow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kopírovat sloupce od.
        '''</summary>
        Friend ReadOnly Property dn_CopyColumnsFrom() As String
            Get
                Return ResourceManager.GetString("dn_CopyColumnsFrom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kultura.
        '''</summary>
        Friend ReadOnly Property dn_Culture() As String
            Get
                Return ResourceManager.GetString("dn_Culture", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Název DataSetu.
        '''</summary>
        Friend ReadOnly Property dn_DatasetName() As String
            Get
                Return ResourceManager.GetString("dn_DatasetName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jmenný prostor DataSetu.
        '''</summary>
        Friend ReadOnly Property dn_DatasetNamespace() As String
            Get
                Return ResourceManager.GetString("dn_DatasetNamespace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Název tabulky v datasetu.
        '''</summary>
        Friend ReadOnly Property dn_datasetTableName() As String
            Get
                Return ResourceManager.GetString("dn_datasetTableName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Formát datumů.
        '''</summary>
        Friend ReadOnly Property dn_DateFormat() As String
            Get
                Return ResourceManager.GetString("dn_DateFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kódování.
        '''</summary>
        Friend ReadOnly Property dn_Encoding() As String
            Get
                Return ResourceManager.GetString("dn_Encoding", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kódování výstupního textu. Například utf-8 nebo windows-1250. Prázdné - použije se výchozí systémové..
        '''</summary>
        Friend ReadOnly Property dn_EncodingCsv() As String
            Get
                Return ResourceManager.GetString("dn_EncodingCsv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Patička.
        '''</summary>
        Friend ReadOnly Property dn_Footer() As String
            Get
                Return ResourceManager.GetString("dn_Footer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hlavička.
        '''</summary>
        Friend ReadOnly Property dn_Header() As String
            Get
                Return ResourceManager.GetString("dn_Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Velikost záhlaví.
        '''</summary>
        Friend ReadOnly Property dn_HeaderSize() As String
            Get
                Return ResourceManager.GetString("dn_HeaderSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vkládat řádky.
        '''</summary>
        Friend ReadOnly Property dn_InsertRows() As String
            Get
                Return ResourceManager.GetString("dn_InsertRows", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to List.
        '''</summary>
        Friend ReadOnly Property dn_List() As String
            Get
                Return ResourceManager.GetString("dn_List", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Názvy.
        '''</summary>
        Friend ReadOnly Property dn_NameColumn() As String
            Get
                Return ResourceManager.GetString("dn_NameColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Název listu.
        '''</summary>
        Friend ReadOnly Property dn_NameColumns() As String
            Get
                Return ResourceManager.GetString("dn_NameColumns", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Formát názvu.
        '''</summary>
        Friend ReadOnly Property dn_NameFormat() As String
            Get
                Return ResourceManager.GetString("dn_NameFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Určuje znak pro použití nového řádku. Možné jsou všechny oddělovače podporované Unicode..
        '''</summary>
        Friend ReadOnly Property dn_NewLine() As String
            Get
                Return ResourceManager.GetString("dn_NewLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Escape nového řádku.
        '''</summary>
        Friend ReadOnly Property dn_NlEscape() As String
            Get
                Return ResourceManager.GetString("dn_NlEscape", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Null.
        '''</summary>
        Friend ReadOnly Property dn_NullValue() As String
            Get
                Return ResourceManager.GetString("dn_NullValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Formát čísel.
        '''</summary>
        Friend ReadOnly Property dn_NumberFormat() As String
            Get
                Return ResourceManager.GetString("dn_NumberFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Postrocesovací kód.
        '''</summary>
        Friend ReadOnly Property dn_PostProcessingCode() As String
            Get
                Return ResourceManager.GetString("dn_PostProcessingCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Oblast tisku.
        '''</summary>
        Friend ReadOnly Property dn_PrintArea() As String
            Get
                Return ResourceManager.GetString("dn_PrintArea", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Řádek 1.
        '''</summary>
        Friend ReadOnly Property dn_Row1() As String
            Get
                Return ResourceManager.GetString("dn_Row1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Spustit makro.
        '''</summary>
        Friend ReadOnly Property dn_RunMacroAfter() As String
            Get
                Return ResourceManager.GetString("dn_RunMacroAfter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aktivní list.
        '''</summary>
        Friend ReadOnly Property dn_SelectList() As String
            Get
                Return ResourceManager.GetString("dn_SelectList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Oddělovač.
        '''</summary>
        Friend ReadOnly Property dn_Separator() As String
            Get
                Return ResourceManager.GetString("dn_Separator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vynechat.
        '''</summary>
        Friend ReadOnly Property dn_SkipColumns() As String
            Get
                Return ResourceManager.GetString("dn_SkipColumns", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vynechat vyplněné sloupce.
        '''</summary>
        Friend ReadOnly Property dn_SkipFilled() As String
            Get
                Return ResourceManager.GetString("dn_SkipFilled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jen chybějící názvy.
        '''</summary>
        Friend ReadOnly Property dn_SkipFilledName() As String
            Get
                Return ResourceManager.GetString("dn_SkipFilledName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Speciální řetězec.
        '''</summary>
        Friend ReadOnly Property dn_SpecialString() As String
            Get
                Return ResourceManager.GetString("dn_SpecialString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pozastavit přepočítávání.
        '''</summary>
        Friend ReadOnly Property dn_SuspendRecalculations() As String
            Get
                Return ResourceManager.GetString("dn_SuspendRecalculations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Textový kvalifikátor.
        '''</summary>
        Friend ReadOnly Property dn_TextQualifier() As String
            Get
                Return ResourceManager.GetString("dn_TextQualifier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Escape textového kvalifikátoru.
        '''</summary>
        Friend ReadOnly Property dn_TextQualifierEscape() As String
            Get
                Return ResourceManager.GetString("dn_TextQualifierEscape", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Použit kvalifikátor.
        '''</summary>
        Friend ReadOnly Property dn_TextQualifierUsage() As String
            Get
                Return ResourceManager.GetString("dn_TextQualifierUsage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zapisovat rozklad.
        '''</summary>
        Friend ReadOnly Property dn_WriteBreak() As String
            Get
                Return ResourceManager.GetString("dn_WriteBreak", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zapisovat název.
        '''</summary>
        Friend ReadOnly Property dn_WriteName() As String
            Get
                Return ResourceManager.GetString("dn_WriteName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to XML prefix.
        '''</summary>
        Friend ReadOnly Property dn_XmlPrefix() As String
            Get
                Return ResourceManager.GetString("dn_XmlPrefix", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to V uživatelském kódu pro postprocessing došlo k chybě {0} {1}.
        '''</summary>
        Friend ReadOnly Property ex_ErrorInUserPostprocessingCode() As String
            Get
                Return ResourceManager.GetString("ex_ErrorInUserPostprocessingCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to V sešitu není dostatek listů pro index .
        '''</summary>
        Friend ReadOnly Property ex_ExcelListIndexOutOfRange() As String
            Get
                Return ResourceManager.GetString("ex_ExcelListIndexOutOfRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vlastnost newline má nepodporovanou hodnotu.
        '''</summary>
        Friend ReadOnly Property ex_NewLineInvalidValue() As String
            Get
                Return ResourceManager.GetString("ex_NewLineInvalidValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Operace stornována.
        '''</summary>
        Friend ReadOnly Property ex_OperationCancelled() As String
            Get
                Return ResourceManager.GetString("ex_OperationCancelled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sobor šablony nebyl nalezen.
        '''</summary>
        Friend ReadOnly Property ex_TemplateNotFound() As String
            Get
                Return ResourceManager.GetString("ex_TemplateNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Šablona typu {0} ({1}) není podporována jako šablona subreportu se šablonou {2} ({3})..
        '''</summary>
        Friend ReadOnly Property ex_UnsupportedSubreportType() As String
            Get
                Return ResourceManager.GetString("ex_UnsupportedSubreportType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Doplněk aplikace excel.
        '''</summary>
        Friend ReadOnly Property ExcelName_AddInDefault() As String
            Get
                Return ResourceManager.GetString("ExcelName_AddInDefault", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Soubory aplikace Excel.
        '''</summary>
        Friend ReadOnly Property ExcelName_CommonFiles() As String
            Get
                Return ResourceManager.GetString("ExcelName_CommonFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Text oddělený oddělovačem.
        '''</summary>
        Friend ReadOnly Property ExcelName_CSV() As String
            Get
                Return ResourceManager.GetString("ExcelName_CSV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sešit aplikace Excel.
        '''</summary>
        Friend ReadOnly Property ExcelName_Default() As String
            Get
                Return ResourceManager.GetString("ExcelName_Default", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DIF (formát výměny dat).
        '''</summary>
        Friend ReadOnly Property ExcelName_DIF() As String
            Get
                Return ResourceManager.GetString("ExcelName_DIF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Webová stránka.
        '''</summary>
        Friend ReadOnly Property ExcelName_HTML() As String
            Get
                Return ResourceManager.GetString("ExcelName_HTML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Webová stránka tvořená jedním souborem.
        '''</summary>
        Friend ReadOnly Property ExcelName_MHTML() As String
            Get
                Return ResourceManager.GetString("ExcelName_MHTML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OpenDocument Spreadsheet.
        '''</summary>
        Friend ReadOnly Property ExcelName_ODS() As String
            Get
                Return ResourceManager.GetString("ExcelName_ODS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PDF.
        '''</summary>
        Friend ReadOnly Property ExcelName_PDF() As String
            Get
                Return ResourceManager.GetString("ExcelName_PDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Formátovaný text (oddělený mezerami).
        '''</summary>
        Friend ReadOnly Property ExcelName_PRN() As String
            Get
                Return ResourceManager.GetString("ExcelName_PRN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SYLK (symbolické propojení).
        '''</summary>
        Friend ReadOnly Property ExcelName_SLK() As String
            Get
                Return ResourceManager.GetString("ExcelName_SLK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Šablona aplikace Excel.
        '''</summary>
        Friend ReadOnly Property ExcelName_TemplateDefault() As String
            Get
                Return ResourceManager.GetString("ExcelName_TemplateDefault", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Šablony aplikace Excel.
        '''</summary>
        Friend ReadOnly Property ExcelName_TemplatesAll() As String
            Get
                Return ResourceManager.GetString("ExcelName_TemplatesAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Text (oddělený tabulátory).
        '''</summary>
        Friend ReadOnly Property ExcelName_TXT() As String
            Get
                Return ResourceManager.GetString("ExcelName_TXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Doplněk aplikace excel 97-2003.
        '''</summary>
        Friend ReadOnly Property ExcelName_XLAOld() As String
            Get
                Return ResourceManager.GetString("ExcelName_XLAOld", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Binární sešit aplikace Excel.
        '''</summary>
        Friend ReadOnly Property ExcelName_XLSB() As String
            Get
                Return ResourceManager.GetString("ExcelName_XLSB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sešit aplikace Excel s podporou maker.
        '''</summary>
        Friend ReadOnly Property ExcelName_XLSM() As String
            Get
                Return ResourceManager.GetString("ExcelName_XLSM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sešit aplikace Excel 97-2003.
        '''</summary>
        Friend ReadOnly Property ExcelName_XLSOld() As String
            Get
                Return ResourceManager.GetString("ExcelName_XLSOld", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to šablona aplikace Excel s podporou maker.
        '''</summary>
        Friend ReadOnly Property ExcelName_XLTM() As String
            Get
                Return ResourceManager.GetString("ExcelName_XLTM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to šablona aplikace Excel 97-2003.
        '''</summary>
        Friend ReadOnly Property ExcelName_XLTOld() As String
            Get
                Return ResourceManager.GetString("ExcelName_XLTOld", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Datové soubory ve formátu XML.
        '''</summary>
        Friend ReadOnly Property ExcelName_XML() As String
            Get
                Return ResourceManager.GetString("ExcelName_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dokument XPS.
        '''</summary>
        Friend ReadOnly Property ExcelName_XPS() As String
            Get
                Return ResourceManager.GetString("ExcelName_XPS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Excel (opakovaný).
        '''</summary>
        Friend ReadOnly Property ExcelRepeated() As String
            Get
                Return ResourceManager.GetString("ExcelRepeated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Excel (jednoduchý).
        '''</summary>
        Friend ReadOnly Property ExcelSimple() As String
            Get
                Return ResourceManager.GetString("ExcelSimple", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hodnoty oddělené oddělovačem (*.csv)|*.csv|Hodnoty oddělené tabulátorem (*.tsv)|*.tsv|Textové soubory (*.txt)|*.txt.
        '''</summary>
        Friend ReadOnly Property filter_CSVTSVTSXT() As String
            Get
                Return ResourceManager.GetString("filter_CSVTSVTSXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Soubory XML (*.xml)|*.xml.
        '''</summary>
        Friend ReadOnly Property filter_XML() As String
            Get
                Return ResourceManager.GetString("filter_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0},{1}: {2} - {3}.
        '''</summary>
        Friend ReadOnly Property msg_CompilerWarningLog() As String
            Get
                Return ResourceManager.GetString("msg_CompilerWarningLog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba v uživatelském kódu {0}: {1} @ {2}.
        '''</summary>
        Friend ReadOnly Property msg_ErrorInUserCode() As String
            Get
                Return ResourceManager.GetString("msg_ErrorInUserCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exportuji XML.
        '''</summary>
        Friend ReadOnly Property msg_ExportingXml() As String
            Get
                Return ResourceManager.GetString("msg_ExportingXml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dokončování listu {0}, šablona {1}.
        '''</summary>
        Friend ReadOnly Property msg_FinalizeTemplateList() As String
            Get
                Return ResourceManager.GetString("msg_FinalizeTemplateList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generování šablony {0}.
        '''</summary>
        Friend ReadOnly Property msg_GeneratingTemplate() As String
            Get
                Return ResourceManager.GetString("msg_GeneratingTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Načítám data z databáze.
        '''</summary>
        Friend ReadOnly Property msg_LoadingDataFromDatabase() As String
            Get
                Return ResourceManager.GetString("msg_LoadingDataFromDatabase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Načítám XSLT šablonu.
        '''</summary>
        Friend ReadOnly Property msg_LoadingXsltTemplate() As String
            Get
                Return ResourceManager.GetString("msg_LoadingXsltTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Příprava šablony {0}.
        '''</summary>
        Friend ReadOnly Property msg_PreparingTemplate() As String
            Get
                Return ResourceManager.GetString("msg_PreparingTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Příprava šablony {0}, list {1}.
        '''</summary>
        Friend ReadOnly Property msg_PreparingTemplateList() As String
            Get
                Return ResourceManager.GetString("msg_PreparingTemplateList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ukládám XML.
        '''</summary>
        Friend ReadOnly Property msg_SavingXml() As String
            Get
                Return ResourceManager.GetString("msg_SavingXml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Subreporty šablony {0}.
        '''</summary>
        Friend ReadOnly Property msg_SubreportsOfTemplate() As String
            Get
                Return ResourceManager.GetString("msg_SubreportsOfTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zápis dat šablony {0}, list {1}.
        '''</summary>
        Friend ReadOnly Property msg_WritingTemplateList() As String
            Get
                Return ResourceManager.GetString("msg_WritingTemplateList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to přepočet....
        '''</summary>
        Friend ReadOnly Property Recomputing() As String
            Get
                Return ResourceManager.GetString("Recomputing", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
